import booking from './booking.html';
import characteristics from './characteristics.html';
import column from './column.html';
import columnsMenu from './columnsMenu.html';
import contacts from './contacts.html';
import countdown from './countdownBlock.html';
import cover from './cover.html';
import coverCarousel from './coverCarousel.html';
import delimiter from './delimiter.html';
import exit from './exit.html';
import footer from './footer.html';
import form from './formBlock.html';
import gallery from './gallery.html';
import galleryWithTExt from './galleryWithTExt.html';
import header from './header.html';
import html from './html.html';
import image from './image.html';
import logos from './logos.html';
import news from './news.html';
import personalAccount from './personalAccount.html';
import productsByCategories from './productsByCategories.html';
import productsView from './productsView.html';
import productsViewLead from './productsViewLead.html';
import progressbar from './progressbar.html';
import quiz from './quiz.html';
import reference from './reference.html';
import reviews from './reviews.html';
import reviewsByUsers from './reviewsByUsers.html';
import reviewsWithRating from './reviewsWithRating.html';
import schedule from './schedule.html';
import scheduleAlt from './scheduleAlt.html';
import scheduleWithTitle from './scheduleWithTitle.html';
import services from './services.html';
import servicesColumns from './servicesColumns.html';
import servicesColumnsThreeIcons from './servicesColumnsThreeIcons.html';
import servicesGroup from './servicesGroup.html';
import servicesGroupAccordion from './servicesGroupAccordion.html';
import servicesLinks from './servicesLinks.html';
import servicesTable from './servicesTable.html';
import socialButtons from './socialButtons.html';
import team from './team.html';
import text from './text.html';
import video from './video.html';
import videoColumns from './videoColumns.html';
import donate from './donate.html';

const templatesList = new Map();

templatesList.set('booking', booking);
templatesList.set('characteristics', characteristics);
templatesList.set('column', column);
templatesList.set('columnsMenu', columnsMenu);
templatesList.set('contacts', contacts);
templatesList.set('countdown', countdown);
templatesList.set('cover', cover);
templatesList.set('coverCarousel', coverCarousel);
templatesList.set('delimiter', delimiter);
templatesList.set('exit', exit);
templatesList.set('footer', footer);
templatesList.set('form', form);
templatesList.set('gallery', gallery);
templatesList.set('galleryWithText', galleryWithTExt);
templatesList.set('header', header);
templatesList.set('html', html);
templatesList.set('image', image);
templatesList.set('logos', logos);
templatesList.set('news', news);
templatesList.set('personalAccount', personalAccount);
templatesList.set('productsByCategories', productsByCategories);
templatesList.set('productsView', productsView);
templatesList.set('productsViewLead', productsViewLead);
templatesList.set('progressbar', progressbar);
templatesList.set('quiz', quiz);
templatesList.set('reference', reference);
templatesList.set('reviews', reviews);
templatesList.set('reviewsByUsers', reviewsByUsers);
templatesList.set('reviewsWithRating', reviewsWithRating);
templatesList.set('schedule', schedule);
templatesList.set('scheduleAlt', scheduleAlt);
templatesList.set('scheduleWithTitle', scheduleWithTitle);
templatesList.set('services', services);
templatesList.set('servicesColumns', servicesColumns);
templatesList.set('servicesColumnsThreeIcons', servicesColumnsThreeIcons);
templatesList.set('servicesGroup', servicesGroup);
templatesList.set('servicesGroupAccordion', servicesGroupAccordion);
templatesList.set('servicesLinks', servicesLinks);
templatesList.set('servicesTable', servicesTable);
templatesList.set('socialButtons', socialButtons);
templatesList.set('team', team);
templatesList.set('text', text);
templatesList.set('video', video);
templatesList.set('videoColumns', videoColumns);
templatesList.set('donate', donate);

export default templatesList;
